config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'leaderboard#index'
  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'

  resources :games, only: [:new, :create]
  resources :history, only: :index, path: 'your-history'
end

app/models/game.rb
class Game < ActiveRecord::Base
  DEFAULT_SCORE_PER_GAME = 50

  belongs_to :opponent, class_name: User
  belongs_to :user

  validates :date_played, :your_score, :their_score, :user, :opponent, presence: true
  validates :your_score, :their_score, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate :scores_meet_rules

  after_validation :set_victory
  after_save :set_users_score, :update_rankings

  private

  def set_users_score
    if self.victory?
      set_winner_score
    else
      set_opponent_score
    end
  end

  def set_winner_score
    user_ranking = user.ranking
    opponent_ranking = opponent.ranking

    if user_ranking >= opponent_ranking
      user.score += DEFAULT_SCORE_PER_GAME
    else
      difference = opponent_ranking - user_ranking
      user.score += DEFAULT_SCORE_PER_GAME * difference
    end

    user.save
  end

  def set_opponent_score
    user_ranking = user.ranking
    opponent_ranking = opponent.ranking

    if opponent_ranking >= user_ranking
      opponent.score += DEFAULT_SCORE_PER_GAME
    else
      difference = user_ranking - opponent_ranking
      opponent.score += DEFAULT_SCORE_PER_GAME * difference
    end

    opponent.save
  end

  def update_rankings
    users = User.all.order('score DESC')

    users.each_with_index do |user, index|
      user.update_attribute :ranking, index + 1
    end
  end

  def set_victory
    self.victory =  self.your_score > self.their_score
  end

  def scores_meet_rules
    difference = (self.your_score - self.their_score).abs

    if difference < 2
      errors.add(:scores, "don't meet the rules")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable

  def games
    Game.where('opponent_id = ? OR user_id = ?', id, id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
    @game.user = current_user
  end

  def create
    @game = Game.new(user: current_user)
    @game.update_attributes game_params

    if @game.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def game_params
    params.require(:game).permit(
      :date_played,
      :opponent_id,
      :your_score,
      :their_score
    )
  end
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  def index
    @games = current_user.games.includes(:opponent).order('date_played DESC')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def history
  end

  def log
  end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def index
    @users = User.all.order('score DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def opponent_options
    users = User.where.not(email: current_user.email)
    users.map { |u| [u.email, u.id] }
  end
end

app/views/games/new.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <%- unless @game.errors.empty? %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>
          <strong>The following errors occurred</strong>
        </p>
        <%- @game.errors.messages.each do |m| %>
          <p><%= "#{m[0]} #{m[1][0]}" %></p>
        <%- end %>
      </div>
    <%- end %>

    <%= form_for @game, url: { action: 'create' }, html: { class: 'form-horizontal' } do |f| %>
      <div class="form-group">
        <%= f.label :date_played %>
        <%= f.date_field :date_played, class: 'form-control', placeholder: 'Date Played' %>
      </div>
      <div class="form-group">
        <%= f.select :opponent_id, options_for_select(opponent_options), { prompt: 'Choose the opponent' }, { class: 'form-control' } %>
      </div>
      <div class="form-group">
        <%= f.label :your_score %>
        <%= f.number_field :your_score, class: 'form-control', placeholder: 'Your score', min: 0 %>
      </div>
      <div class="form-group">
        <%= f.label :their_score %>
        <%= f.number_field :their_score, class: 'form-control', placeholder: 'Their score', min: 0 %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-primary' %>
        <%= link_to 'Cancel', root_path, class: 'btn btn-danger' %>
      </div>
    <%- end %>
  </div>
</div>

app/views/history/index.html.erb
<h1 class='page-header'>History</h1>

<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <%- unless @games.empty? %>
      <table class="table table-striped">
        <thead>
          <th>Date</th>
          <th>Opponent</th>
          <th>Score</th>
          <th>Result</th>
        </thead>
        <tbody>
          <%- @games.each do |game| %>
            <tr>
              <td><%= game.date_played %></td>
              <td><%= game.opponent.email %></td>
              <td><%= game.your_score %> - <%= game.their_score %></td>
              <td><%= game.victory? ? 'W' : 'L' %></td>
            </tr>
          <%- end %>
        </tbody>
      </table>
    <%- else %>
      <p class="text-center">
        <strong>You haven't played a match yet.</strong>
      </p>
    <%- end %>
  </div>
</div>

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('history.png') %>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<div class="alert alert-warning" role="alert">This is a sample page.</div>

<%= image_tag('leaderboard.png') %>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', new_game_path, class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'History', history_index_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/leaderboard/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <table class="table table-striped">
      <thead>
        <th>Rank</th>
        <th>Email</th>
        <th>Score</th>
        <th>Games Played</th>
      </thead>
      <tbody>
        <%- @users.each_with_index do |user| %>
          <tr>
            <td><%= user.ranking %></td>
            <td><%= user.email %></td>
            <td><%= user.score %></td>
            <td><%= user.games.count %></td>
          </tr>
        <%- end %>
      </tbody>
    </table>
  </div>
</div>